### ISSUE TITLE
При большом кол-ве свойств дестуктуризации их записывают на отдельной строке

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_react_youtube-search#2]
https://github.com/lyolka92/epam_react_youtube-search/blob/ae40b0bf9251f592a47d7f33c41008642dee4a73/src/api/search-service.js#L50

```
    const {
       title, 
       channelTitle: author,
       publishedAt: uploadDate,
       description,
    } = video.snippet;
```

**Comment by lyolka92** [comment]
Настроила eslint и prettier - теперь они за меня красоту наводят
