### ISSUE TITLE
Нужно передавать еще массив зависимостей, иначе useEffect будет постоянно срабатывать

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_react_youtube-search#5]
https://github.com/lyolka92/epam_react_youtube-search/blob/ae40b0bf9251f592a47d7f33c41008642dee4a73/src/components/Slider.js#L37

https://ru.reactjs.org/docs/hooks-effect.html

**Comment by lyolka92** [comment]
По совету  exhaustive-deps из линтера eslint-plugin-react-hooks добавила в засисимости dispatch
