### ISSUE TITLE
Может быть лучше VideoSlide?

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_react_youtube-search#6]
https://github.com/lyolka92/epam_react_youtube-search/blob/ae40b0bf9251f592a47d7f33c41008642dee4a73/src/components/Slider.js#L74

**Comment by lyolka92** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/58735478/88036425-3546b200-cb4c-11ea-8d83-3faef61d4b57.png">
Думаю, что в текущей структуре, как саб-компонент, SliderVideo смотрится неплохо
