### ISSUE TITLE
Уже скидывал статью про export default

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_react_youtube-search#7]
https://github.com/lyolka92/epam_react_youtube-search/blob/ae40b0bf9251f592a47d7f33c41008642dee4a73/src/components/Slider.js#L87

https://medium.com/@Brisstor/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%B8%D1%81%D1%8C-%D0%BE%D1%82-export-default-%D0%B2-javascript-%D0%B8-%D0%B2%D0%B0%D0%BC-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B8%D1%82%D1%8C-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5-cce6ac30d67b

**Comment by lyolka92** [comment]
Я подумала, что в React так принято) Везде убрала.
