### ISSUE TITLE
Есть более красивый паттерн для propTypes

### ISSUE THREAD

**Issue by kagegrifon** [lyolka92/epam_react_youtube-search#9]
https://github.com/lyolka92/epam_react_youtube-search/blob/ae40b0bf9251f592a47d7f33c41008642dee4a73/src/components/SliderVideo.js#L43

Чтобы было удобнее читать propTypes
```
const propsTypes = {
 ....
}

export const SliderVideo = () => {
}

SliderVideo.propTypes = propsTypes;
```

при TypeScript propTypes уже не используют

**Comment by lyolka92** [comment]
Попробовала - действительно более симпатично получается. Сейчас в проекте этого уже нет, ибо прикручен ts.
